# Generated by Django 4.2.6 on 2023-11-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_profileinfo_age_alter_profileinfo_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='degree',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='workplace',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
