# Generated by Django 4.2.6 on 2023-11-16 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_profileinfo_address_alter_profileinfo_degree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinfo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profileinfo',
            name='surname',
        ),
    ]
