# Generated by Django 4.2.6 on 2023-12-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_media_media_alter_profileinfo_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='last_message_date',
            field=models.DateTimeField(),
        ),
    ]
