# Generated by Django 4.2.6 on 2023-12-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_friend_last_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='profile_image',
            field=models.FileField(blank=True, default='/profile_images/default.png', null=True, upload_to='profile_images/'),
        ),
    ]
